CC=gcc
all: main.c parser.c ../daemon/daemon.c ../config/config.c ../database/fsdb.c ../pack/pack.c ../answer/answer.c
	$(CC) -o parser main.c parser.c ../daemon/daemon.c ../config/config.c ../database/fsdb.c ../pack/pack.c ../answer/answer.c
clean:
	rm parser
